accountServiceUrl: http://account-s
inventoryServiceUrl: http://inventory-s
orderServiceUrl: http://order-s
paymentServiceUrl: http://payment-s

homePage.message: Application is running on port ${server.port}
